# Generated by Django 5.1.5 on 2025-04-08 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentstatus",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="trip",
            name="guests",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="guests", to="booking_system.guest"
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="payment_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="booking_system.paymentstatus",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="booking_system.tripstatus",
            ),
        ),
    ]
