# Generated by Django 5.1.5 on 2025-04-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booking_system",
            "0002_alter_paymentstatus_description_alter_trip_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tripstatus",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
