# Generated by Django 5.1.5 on 2025-04-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0003_alter_tripstatus_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="booking_system.agent",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="generated",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="booking_system.generated",
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="guests",
            field=models.ManyToManyField(
                blank=True, related_name="guests", to="booking_system.guest"
            ),
        ),
    ]
