# Generated by Django 5.1.5 on 2025-04-08 20:34

from django.db import migrations

def populate_generated(apps, schema_editor):
    Generated = apps.get_model('booking_system', 'Generated')
    titles = [
        "Direct", "Magazine Ad", "Referral", "Google Maps", "Agent"
    ]

    for title in set(titles):  # remove duplicates
        Generated.objects.get_or_create(title=title)



class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0004_trip_agent_trip_generated_alter_trip_guests"),
    ]

    operations = [
        migrations.RunPython(populate_generated)
    ]
