# Generated by Django 5.1.5 on 2025-04-08 20:38

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0005_populate_generated_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agent",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="NO"
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
