# Generated by Django 5.1.5 on 2025-04-08 20:44

from django.db import migrations


def populate_currencies(apps, schema_editor):
    Currency = apps.get_model('booking_system', 'Currency')

    currencies = [
        ("Norwegian Krone", "NOK"),
        ("Danish Krone", "DKK"),
        ("Swedish Krone", "SEK"),
        ("US Dollar", "USD"),
        ("South African Rand", "ZAR"),
        ("Euro", "EUR"),
        ("British Pound", "GBP"),
    ]

    for name, code in currencies:
        Currency.objects.get_or_create(name=name, code=code)

    
class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0006_alter_agent_note_alter_agent_phone_number_and_more"),
    ]

    operations = [migrations.RunPython(populate_currencies)]
