# Generated by Django 5.1.5 on 2025-05-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_system", "0007_populate_currencies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultant",
            name="type",
            field=models.CharField(
                choices=[
                    ("NOR", "Norwegian"),
                    ("ZAR", "South African"),
                    ("OTHER", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="guest",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="guest",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="guests",
            field=models.ManyToManyField(
                blank=True, related_name="trips", to="booking_system.guest"
            ),
        ),
    ]
